import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule],
  template: `<div class="reports-page"><h2>Historical Risk Reports</h2><p class="subtitle">Reports generated by the AI analyst are stored here.</p></div>`,
})
export class ReportsComponent {}
